apiVersion: v1
kind: Service
metadata:
  namespace: cael
  name: my-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 # Incoming
      targetPort: 5432 # outgoing port (pod port)
